export const OverviewArticleData = [
    {
        id: 1,
        IconSocial: 'IconFacebook',
        AltIconSocial: 'Icon Facebook',
        title: 'Page Views',
        Number: 1987,
        UpOrDown: true,
        NewFollowers: '3%',
        State: 'Positive',
    },
    {
        id: 2,
        IconSocial: 'IconFacebook',
        AltIconSocial: 'Icon Facebook',
        title: 'Likes',
        Number: 52,
        UpOrDown: false,
        NewFollowers: '2%',
        State: 'Negative',
    },
    {
        id: 3,
        IconSocial: 'IconInstagram',
        AltIconSocial: 'Icon Instagram',
        title: 'Likes',
        Number: 5462,
        UpOrDown: true,
        NewFollowers: '2257%',
        State: 'Positive',
    },
    {
        id: 4,
        IconSocial: 'IconInstagram',
        AltIconSocial: 'Icon Instagram',
        title: 'Profile Views',
        Number: '52K',
        UpOrDown: true,
        NewFollowers: '1375%',
        State: 'Positive',
    },
    {
        id: 5,
        IconSocial: 'IconTwitter',
        AltIconSocial: 'Icon Twitter',
        title: 'Retweets',
        Number: 117,
        UpOrDown: true,
        NewFollowers: '303%',
        State: 'Positive',
    },
    {
        id: 6,
        IconSocial: 'IconTwitter',
        AltIconSocial: 'Icon Twitter',
        title: 'Likes',
        Number: 507,
        UpOrDown: true,
        NewFollowers: '553%',
        State: 'Positive',
    },
    {
        id: 7,
        IconSocial: 'IconYoutube',
        AltIconSocial: 'Icon Youtube',
        title: 'Likes',
        Number: 107,
        UpOrDown: false,
        NewFollowers: '19%',
        State: 'Negative',
    },
    {
        id: 8,
        IconSocial: 'IconYoutube',
        AltIconSocial: 'Icon Youtube',
        title: 'Total Views',
        Number: 1407,
        UpOrDown: false,
        NewFollowers: '12%',
        State: 'Negative',
    },
];

export const ArticlePrimaryData = [
    {
        id: 1,
        IconSocial: 'IconFacebook',
        AltIconSocial: 'Icon Facebook',
        ClassSocial: 'Facebook',
        Name: '@nathanf',
        Number: 1987,
        UpOrDown: true,
        NewFollowers: 12,
        State: 'Positive',
    },
    {
        id: 2,
        IconSocial: 'IconTwitter',
        AltIconSocial: 'Icon Twitter',
        ClassSocial: 'Twitter',
        Name: '@nathanf',
        Number: 1044,
        UpOrDown: true,
        NewFollowers: 99,
        State: 'Positive',
    },
    {
        id: 3,
        IconSocial: 'IconInstagram',
        AltIconSocial: 'Icon Instagram',
        ClassSocial: 'Instagram',
        Name: '@realnathanf',
        Number: '11k',
        UpOrDown: true,
        NewFollowers: 1099,
        State: 'Positive',
    },
    {
        id: 4,
        IconSocial: 'IconYoutube',
        AltIconSocial: 'Icon Youtube',
        ClassSocial: 'Youtube',
        Name: 'Nathan F.',
        Number: 8239,
        UpOrDown: false,
        NewFollowers: 144,
        State: 'Negative',
    },
];
